### PR TITLE
Information about chocolatey package in README.md

### LINKED ISSUE #12: chocolatey
Pleeeeeeeeeeease publish this to chocolatey :D
Thanks!

### PR DESCRIPTION
**Pull request by abuzhynsky**
Fixes #12 
I've created [Chocolatey package for TailBlazer](https://chocolatey.org/packages/tailblazer). Package configuration can be found [here](https://github.com/abuzhynsky/chocolatey-packages). Packages are produced automatically using Ketarin from TailBlazer releases page. I can maintain this package by myself if you don't mind or I can transfer ownership to you.

### CODE REVIEW

**Comment by RolandPheasant** [comment]
Great stuff. A few people have asked about getting TB in chocolatey so I am very happy that you have taken the case up.

For now I will leave the maintainance to you at least until I know what to do.

**Comment by abuzhynsky** [comment]
Thank you. OK, no problem.

**Comment by RolandPheasant** [comment]
@abuzhynsky there is a new versions of tail blazer out. What is requires to update chocolatey?

**Comment by abuzhynsky** [comment]
@RolandPheasant, unfortunately I'm on vacation right now without my laptop. I can pack new version only on 22nd of February when I return home. I'll try to work it out earlier if I'm lucky with good Internet connection.

**Comment by RolandPheasant** [comment]
No problem. Thanks

**Comment by RolandPheasant** [comment]
@abuzhynsky please let me now when you can upload to chocolatey as I am about to do another release. Thanks

**Comment by abuzhynsky** [comment]
@RolandPheasant, I'll upload 0.6 version tomorrow and I'll upload new release as soon as you create it. Sorry for delay.

**Comment by RolandPheasant** [comment]
:+1:

**Comment by abuzhynsky** [comment]
@RolandPheasant, could you please recreate 0.6 release binaries archive without inner folder (just having binaries in the root of archive)? Chocolatey has an [issue](https://github.com/chocolatey/chocolatey/issues/406) with extracting specific folders from archive.
I'll create 0.6 chocolatey package as soon as you amend this archive.
Also, one more thing - could you please use one naming scheme for release tags and for release binaries archives for further releases?

**Comment by RolandPheasant** [comment]
I did not know there was a sub folder. Will sort it out later

**Comment by RolandPheasant** [comment]
When you say one naming scheme, do you mean an exact version match for the tag and binary. Or do you mean drop the v prefix?

**Comment by abuzhynsky** [comment]
@RolandPheasant 
Ketarin works using regex for automatic creation of Chocolatey packages. It looks for version information and download url.
Regarding tags - you can choose **v0.6** or just **0.6** pattern and use it for further releases. 
Regarding file names - there are **TailBlazerv0.6.zip** and **TailBlazer_v0.4.2.zip**, for example. Just choose one pattern for these file names too. Don't change the names of old versions please to not break existing Chocolatey packages.
Also I think it's better to have full version number (**0.6.340** instead of just **0.6**) in tags - Chocolatey version is based on them.
Thank you.

**Comment by RolandPheasant** [comment]
Got it.

I will do it later. Either shortly after or tomorrow I will release 0.7.

Thx

**Comment by RolandPheasant** [comment]
@abuzhynsky I have update the tags and the zip file for the 0.6 release now. I hope that's what's required

**Comment by RolandPheasant** [comment]
@abuzhynsky hope this does not mess things up but I have just published v0.7. See https://github.com/RolandPheasant/TailBlazer/releases/tag/0.7.0.360

**Comment by abuzhynsky** [comment]
@RolandPheasant thank you, everything is great. 
Yesterday I've created packages for 0.6 and 0.7 versions - they are already in Chocolatey feed, passed automatic validation and are waiting for moderator approve.

**Comment by RolandPheasant** [comment]
Fantastic. Thanks very much

**Comment by abuzhynsky** [comment]
@RolandPheasant Both versions are approved by moderator and can be installed using Chocolatey.

**Comment by RolandPheasant** [comment]
Awesome.

**Pull request merged**
