### PR TITLE
Add Fody/Costura so that dependent assemblies are merged into the EXE

### PR DESCRIPTION
**Pull request by kstrauss**
As a result you can now just move the EXE around and it'll work. Makes it more convient to add to a toolbelt directory like 'util'.

Also added a default for log4net that will out put to win32 debug so you can use dbgview.

I think this makes it more utility like.

### CODE REVIEW

**Comment by CasperTDK** [comment]
I like this +1

**Comment by RolandPheasant** [comment]
That is one rocking pull request.

This is something which I knew I had to consider but was way down my priority so thanks very much

**Comment by kentcb** [comment]
Cool. @kstrauss I'm interested in how this approach compares to using [ILMerge](http://www.microsoft.com/en-au/download/details.aspx?id=17630).

**Comment by kstrauss** [comment]
it follows the advice of Richter as noted here http://blogs.msdn.com/b/microsoft_press/archive/2010/02/03/jeffrey-richter-excerpt-2-from-clr-via-c-third-edition.aspx . I think I read somewhere that if the author of ILMerge knew about his technique he wouldn't have done ILmerge.

I would defer to the documentation (https://github.com/Fody/Costura ), however it does it pretty well as a msbuild task and takes next to no time to do with no prior experience with Fody.

**Comment by RolandPheasant** [comment]
@kstrauss it has worked like a charm. If you don't want to wait for the next release you can grab the single file build from [AppVeyor Build](https://ci.appveyor.com/project/RolandPheasant/tailblazer/build/0.6.253/artifacts)

**Comment by kstrauss** [comment]
Glad to hear it.

If anyone cares about this technique in general, this may not be the correct approach in the future.

What I'm thinking of are the changes that coming down the pipe with .net Native support evolving to make this whole thing into a native executable. Once this is fully in place a similar experience could happen in the standard toolchain (console app support is there and I imagine WPF apps would eventually be enabled too, though it's not currently on the [roadmap](https://github.com/dotnet/core/blob/master/roadmap.md)). At least that's what I was thinking after looking at this.

**Pull request merged**
