### PR TITLE
Add algorithm to find distinct name for tab headers

### PR DESCRIPTION
**Pull request by khellang**
Thought I'd open this ASAP to see if I could get some :eyes: on it.

I think this should fix the first part of #53.

Let me know if this is totally overkill and there's a much easier way to do it :stuck_out_tongue_closed_eyes:

### CODE REVIEW

**Comment by RolandPheasant** [comment]
I've taken the changes without checking first because they are self-standing.  Now in the process of writing more unit tests to check the behaviour.  Will get back to you when I am done

**Comment by RolandPheasant** [comment]
@khellang I see what you have done.  Whilst it does produce distinct paths I think that being as the paths will form a tab header we need to abbreviate the text where possible, so for example if we have

D:\\App\Debug\logger.txt
C:\\App\Debug\logger.txt

it would be great to something like this

D:\\..\logger.txt
C:\\...\logger.txt

or for:

C:\\App\bin\debug\logger.txt
C:\\App\obj\debug\logger.txt

then

bin...logger.txt
obj...logger.txt

Do you think that would be straight forward?

**Comment by khellang** [comment]
> Now in the process of writing more unit tests to check the behaviour.

Yes, that would be awesome :smile:

> Do you think that would be straight forward?

Absolutely. I'll send a PR right away!

**Comment by RolandPheasant** [comment]
Btw what does the 'Trie' post fix mean?

**Comment by khellang** [comment]
Just that it resembles a trie. A very specialized one, though :smile:

**Comment by khellang** [comment]
That's just the underlying data structure, though. It might be worth it to find another name, possibly including the \#1 \#2 thingy (for multiple tabs with same file) as well?

**Comment by RolandPheasant** [comment]
I see, tree!.

**Pull request merged**
