### PR TITLE
Clear file

### PR DESCRIPTION
**Pull request by mgnslndh**
This is a PR for #92 

There are some issues though:

- The button is placed next to "Search options" which makes it possible to clear by misstake.
 - Add question dialog?
 - Move button?
- The file is cleared by deleting it. Not sure if this is what you had in mind. 
- Simple exception handling. Good enough?

### CODE REVIEW

**Comment by RolandPheasant** [comment]
Funny thing is I was intending to look at this one this evening.  What I had in mind was something a little different. Rather than deleting which is not always possible nor desireable, clear could simple start scanning the file from the current last byte position (i.e. file.Length). This would allow for a Clear / UnClear toggle.

In many ways this should be reasonably straight forward.  Currently we have something like this:
```
FileInfo fileInfo =  //....My file
//notifications of file changes
IObservable<FileNotification> notifications = fileInfo .WatchFile();
//for all lines
IObservable<ILineProvider> allines = notifications.Index();
//for filtered lines
IObservable<ILineProvider> filteredlines = notifications.Search(//..text predicate);
```
```.Index()``` and ```Search()``` are frightfully complicated and I regard them as completed so in the spirit of the Open / Close principal, I suggest decorating the results.

```
IObservable<ILineProvider> mySource = filteredlines;  // (or allines);
IObservable<ILineProvider>  cleared = mySource.StartFrom(long startPosition);
```

This concept is testable so could be easily developed in test code and should be reasonable straight for to integrate into the system.

Fancy giving it a go?

**Comment by RolandPheasant** [comment]
@mgnslndh ```IObservable<ILineProvider> ``` is the key interface in this system.  I will also implement a version of it to enable rolled over files to be treated as a single file.

**Comment by mgnslndh** [comment]
I'll give it a try. Can I just revert the previous commit?

**Comment by RolandPheasant** [comment]
Great.

To make life easier, this task can be perceived as 2 task. The first being getting the StartFrom() extension working and tested and the second, integrating it with the UI. When you get nearer to the integration I will explain which code it should be integrated with.

I know a previous commit can be reverted using a command directly using a command. However off the top of my head I cannot remember which command.

**Comment by mgnslndh** [comment]
No, problem, i've reverted the commit. I guess you will merge all commits in a single commit so it really does not matter how my branch history looks like.

I'll try to follow your conventions and add StartFromEx.cs for the StartFrom extension. What does the `startPosition` parameter refer to? The line number or something else?

**Comment by RolandPheasant** [comment]
The last position in bytes of the file which can be obtained using streamreadextended. This will be used as an offset from where to start reading and scanning a file.

Being as the operator is isolated, I would be happy to take the operator only as a first PR. That provides scope for refinement and collaboration.

**Comment by mgnslndh** [comment]
Also, I guess I need to implement a custom `ILineProvider`

**Comment by RolandPheasant** [comment]
That's correct. It should accept an existing line provider as a parameter. 

I

**Pull request merged**
